### ISSUE TITLE
TypeError: thisPromise.then is not a function

### ISSUE THREAD

**Issue by yuta0801** [mokkabonna/inquirer-autocomplete-prompt#56]
# Code
```js
const inquirer = require('inquirer')
const autocomplete = require('inquirer-autocomplete-prompt')

const array = ['red', 'green', 'blue', 'yellow']

inquirer.registerPrompt('autocomplete', autocomplete)
inquirer.prompt({
  type: 'autocomplete',
  name: 'server',
  message: 'Select a server to sync mods with',
  source: (answersSoFar, input) => {
    return array.filter(e => e.startsWith(input))
  },
})

process.on('unhandledRejection', err => console.log(err))
```
# Error
```
TypeError: thisPromise.then is not a function
    at Prompt.search (D:\Yuta\Desktop\node_modules\inquirer-autocomplete-prompt\index.js:186:22)
    at Prompt._run (D:\Yuta\Desktop\node_modules\inquirer-autocomplete-prompt\index.js:71:8)
    at Prompt.<anonymous> (D:\Yuta\Desktop\node_modules\inquirer-autocomplete-prompt\node_modules\inquirer\lib\prompts\base.js:56:10)
    at new Promise (<anonymous>)
    at Prompt.run (D:\Yuta\Desktop\node_modules\inquirer-autocomplete-prompt\node_modules\inquirer\lib\prompts\base.js:55:10)
    at DeferSubscriber.Rx.Observable.defer [as factory] (D:\Yuta\Desktop\node_modules\inquirer\lib\ui\prompt.js:84:27)
    at DeferSubscriber._callFactory (D:\Yuta\Desktop\node_modules\rxjs\observable\DeferObservable.js:92:27)
    at DeferSubscriber.tryDefer (D:\Yuta\Desktop\node_modules\rxjs\observable\DeferObservable.js:85:18)
    at new DeferSubscriber (D:\Yuta\Desktop\node_modules\rxjs\observable\DeferObservable.js:81:14)
    at DeferObservable._subscribe (D:\Yuta\Desktop\node_modules\rxjs\observable\DeferObservable.js:71:16)
```

**Comment by yuta0801** [comment]
I try to return a promise, it's running.
```js,diff
  const inquirer = require('inquirer')
  const autocomplete = require('inquirer-autocomplete-prompt')

  const array = ['red', 'green', 'blue', 'yellow']

  inquirer.registerPrompt('autocomplete', autocomplete)
  inquirer.prompt({
    type: 'autocomplete',
    name: 'server',
    message: 'Select a server to sync mods with',
//  source: (answersSoFar, input) => {
    source: async (answersSoFar, input) => {
      console.log(answersSoFar, input)
      return array.filter(e => e.startsWith(input))
    },
  })

  process.on('unhandledRejection', err => console.log(err))
```
