### ISSUE TITLE
Error: Cannot find module 'rxjs/operators'

### ISSUE THREAD

**Issue by UnleashedMind** [mokkabonna/inquirer-autocomplete-prompt#71]
got this error when the module is invoked. 

Error: Cannot find module 'rxjs/operators'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/mypackage/node_modules/inquirer-autocomplete-prompt/index.js:16:21)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by UnleashedMind** [comment]
after update the inquirer version to  6.0.0, the above error is gone.

**Comment by thierrymichel** [comment]
It is missing again with `inquirer@7.0.x`.
